mykc:
  realmId: myrealm
  users:
    - name: oauth2-proxy-login
      firstName: oauth2
      lastName: proxy
      email: "oauth2@oauth2.com"
      password: "testPassword"

oauth2-proxy:
  config:
    clientID: oauth2-proxy
    clientSecret: testPassword
    configFile: |
      provider = "keycloak-oidc"
      provider_display_name = "Keycloak"
      redirect_url = "http://oauth2-proxy/oauth2/callback"
      oidc_issuer_url = "http://keycloak-app/realms/myrealm"
      code_challenge_method = "S256"
      whitelist_domains = ["*"]
      email_domains = ["*"]
      cookie_domains = ["."]
      cookie_expire = "1h"
      session_cookie_minimal = "true"
      cookie_secure = "false"
      upstreams = [ "http://dummy-nginx-service" ]

keycloak:
  auth:
    adminUser: "admin"
    adminPassword: "HiMom!"
  postgresql:
    enabled: true
    auth:
      postgresPassword: "keycloak"
      username: keycloak
      password: "keycloak"
      database: keycloak
      existingSecret: ""
    architecture: standalone
