---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: "{{ .Release.Name }}-keycloak-config"
  namespace: "{{ .Release.Namespace }}"
spec:
  credentials:
    source: Secret
    secretRef:
      name: "{{ .Release.Name }}-keycloak-credentials"
      key: keycloak-credentials
      namespace: "{{ .Release.Namespace }}"
