---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-keycloak-initial-passwords"
type: Opaque
stringData:
  {{- range $user := $.Values.mykc.users }}

  {{ if hasKey $user "password"}}
  {{$user.name}}: {{$user.password}}
  {{else}}
  {{ if not $.Release.IsUpgrade }}
  {{$user.name}}: {{ default (randAlphaNum 32) }}
  {{end}}
  {{end}}
  {{- end }}

{{- range $user := .Values.mykc.users }}
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: {{ $user.name }}
spec:
  forProvider:
    realmId: {{ $.Values.mykc.realmId }}
    username: {{ $user.name }}
    
    enabled: true
    emailVerified: true
    firstName: {{ $user.firstName }} 
    lastName: {{ $user.lastName }} 
    email: {{ $user.email }} 
    initialPassword:
      - valueSecretRef:
          name: "{{ $.Release.Name }}-keycloak-initial-passwords"
          key: {{ $user.name }}
          namespace: {{ $.Release.Namespace }}
        temporary: false
  deletionPolicy: "Delete"
  providerConfigRef:
    name: "{{ $.Release.Name }}-keycloak-config"
{{- end }}