---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-keycloak-credentials"
type: Opaque
stringData:
  keycloak-credentials: |
    {
      "username":{{ .Values.keycloak.auth.adminUser | quote }},
      "client_id": "admin-cli",
      "password":{{ .Values.keycloak.auth.adminPassword | quote }},
      "url": "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local",
      "realm": "master",
      "tls_insecure_skip_verify": "true"
    }
