---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.x.x
    helm:
      values: |
        provider:
          packages:
            - xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.20.0
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true